# Generated by Django 3.1.7 on 2021-03-02 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='default_profile.png', null=True, upload_to='users/%Y/%m/%d'),
        ),
    ]
